### ISSUE TITLE
a quoi sert la 4eme branche !!??

### ISSUE THREAD

**Issue by allido808** [othmane-boudiab/portfolio#2]
normalement on a 3 branche : main - test -dev . we should delete it !!

**Comment by othmane-boudiab** [comment]
ok

**Comment by Anass-sudo** [comment]
Salut , 
Bravo hamza (eyes-eagle)  , J'ai pas remarqué qu'on a 4 branches ... tt simplement othmane vas le supprimer
Merci

**Comment by allido808** [comment]
done
